version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: maple-db
    restart: always

  gateway:
    build:
      context: ./gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - event
    env_file:
      - ./gateway/.env.docker

  auth:
    build:
      context: ./auth
    ports:
      - '3100:3100'
    depends_on:
      - mongo
    env_file:
      - ./auth/.env.docker

  event:
    build:
      context: ./event
    ports:
      - '3200:3200'
    depends_on:
      - mongo
    env_file:
      - ./event/.env.docker
